openapi: 3.1.0
info:
  title: API
  version: latest
externalDocs:
  url: /
servers: []
tags: []
paths:
  /api/v2/tiltaksgjennomforinger/{id}:
    get:
      tags:
      - Tiltaksgjennomforing
      operationId: getTiltaksgjennomforingV2
      parameters:
      - name: id
        in: path
        required: true
        deprecated: false
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Gjennomføringen
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TiltaksgjennomforingV2Dto"
        "404":
          description: Gjennomføringen ble ikke funnet
          headers: {}
      deprecated: false
  /api/v1/tiltaksgjennomforinger/id/{arenaId}:
    get:
      tags:
      - Tiltaksgjennomforing
      operationId: getTiltaksgjennomforingId
      parameters:
      - name: arenaId
        in: path
        required: true
        deprecated: false
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Id til tiltaksgjennomføringen
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExchangeArenaIdForIdResponse"
        "404":
          description: Gjennomføringen ble ikke funnet
          headers: {}
      deprecated: false
  /api/v1/tiltaksgjennomforinger/arenadata/{id}:
    get:
      tags:
      - Tiltaksgjennomforing
      operationId: getTiltaksgjennomforingArenadata
      parameters:
      - name: id
        in: path
        required: true
        deprecated: false
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Arenadata for tiltaksgjennføringen
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TiltaksgjennomforingArenaDataDto"
        "404":
          description: Gjennomføringen ble ikke funnet
          headers: {}
      deprecated: false
components:
  schemas:
    OpenApiVersion:
      type: number
      enum:
        - 1
    TiltaksgjennomforingV2.Enkeltplass:
      type: object
      properties:
        id:
          type: string
          format: uuid
        opprettetTidspunkt:
          type: string
          format: date-time
        oppdatertTidspunkt:
          type: string
          format: date-time
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"
        arrangor:
          $ref: "#/components/schemas/TiltaksgjennomforingV2Dto.Arrangor"
      required:
      - arrangor
      - id
      - oppdatertTidspunkt
      - opprettetTidspunkt
      - tiltakskode
    Tiltakskode:
      type: string
      enum:
      - ARBEIDSFORBEREDENDE_TRENING
      - ARBEIDSRETTET_REHABILITERING
      - AVKLARING
      - DIGITALT_OPPFOLGINGSTILTAK
      - JOBBKLUBB
      - OPPFOLGING
      - VARIG_TILRETTELAGT_ARBEID_SKJERMET
      - ARBEIDSMARKEDSOPPLAERING
      - ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING
      - ENKELTPLASS_FAG_OG_YRKESOPPLAERING
      - FAG_OG_YRKESOPPLAERING
      - GRUPPE_ARBEIDSMARKEDSOPPLAERING
      - GRUPPE_FAG_OG_YRKESOPPLAERING
      - HOYERE_UTDANNING
      - HOYERE_YRKESFAGLIG_UTDANNING
      - NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV
      - STUDIESPESIALISERING
    TiltaksgjennomforingV2Dto.Arrangor:
      type: object
      properties:
        organisasjonsnummer:
          type: string
      required:
      - organisasjonsnummer
    TiltaksgjennomforingV2.Gruppe:
      type: object
      properties:
        id:
          type: string
          format: uuid
        opprettetTidspunkt:
          type: string
          format: date-time
        oppdatertTidspunkt:
          type: string
          format: date-time
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"
        arrangor:
          $ref: "#/components/schemas/TiltaksgjennomforingV2Dto.Arrangor"
        navn:
          type: string
        startDato:
          type: string
          format: date
        sluttDato:
          type:
          - "null"
          - string
          format: date
        status:
          $ref: "#/components/schemas/GjennomforingStatusType"
        oppstart:
          $ref: "#/components/schemas/GjennomforingOppstartstype"
        pameldingType:
          $ref: "#/components/schemas/GjennomforingPameldingType"
        tilgjengeligForArrangorFraOgMedDato:
          type:
          - "null"
          - string
          format: date
        apentForPamelding:
          type: boolean
        antallPlasser:
          type: integer
          format: int32
        deltidsprosent:
          type: number
          format: double
        oppmoteSted:
          type:
          - "null"
          - string
      required:
      - antallPlasser
      - apentForPamelding
      - arrangor
      - deltidsprosent
      - id
      - navn
      - oppdatertTidspunkt
      - oppmoteSted
      - opprettetTidspunkt
      - oppstart
      - pameldingType
      - sluttDato
      - startDato
      - status
      - tilgjengeligForArrangorFraOgMedDato
      - tiltakskode
    GjennomforingStatusType:
      type: string
      enum:
      - GJENNOMFORES
      - AVSLUTTET
      - AVBRUTT
      - AVLYST
    GjennomforingOppstartstype:
      type: string
      enum:
      - LOPENDE
      - FELLES
      - ENKELTPLASS
    GjennomforingPameldingType:
      type: string
      enum:
      - DIREKTE_VEDTAK
      - TRENGER_GODKJENNING
    TiltaksgjennomforingV2Dto:
      anyOf:
      - $ref: "#/components/schemas/TiltaksgjennomforingV2.Enkeltplass"
      - $ref: "#/components/schemas/TiltaksgjennomforingV2.Gruppe"
      discriminator:
        propertyName: type
        mapping:
          TiltaksgjennomforingV2.Enkeltplass: "#/components/schemas/TiltaksgjennomforingV2.Enkeltplass"
          TiltaksgjennomforingV2.Gruppe: "#/components/schemas/TiltaksgjennomforingV2.Gruppe"
    ExchangeArenaIdForIdResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
      - id
    TiltaksgjennomforingArenaDataDto:
      type: object
      properties:
        opprettetAar:
          type: integer
          format: int32
        lopenr:
          type: integer
          format: int32
      required:
      - lopenr
      - opprettetAar
  examples: {}
webhooks: {}
