name: Deploy alerts

on:
  push:
    paths:
      - .github/workflows/deploy-alerts.yaml
      - iac/alerts/**

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: iac/alerts

  deploy-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: iac/alerts/alerts-dev.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: iac/alerts/alerts-prod.yaml
