name: CI/CD (nav-enheter-to-sanity)

on:
  push:
    paths:
      - .github/workflows/nav-enheter-to-sanity.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/nav-enheter-to-sanity/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/navikt/mulighetsrommet/nav-enheter-to-sanity:${{ github.sha }}
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run lint build --filter=nav-enheter-to-sanity
      - name: Build and publish Docker image
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
        working-directory: frontend/nav-enheter-to-sanity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker build --pull -t ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy (dev)
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: frontend/nav-enheter-to-sanity/.nais/nais-dev.yaml
          VAR: image=${{ env.IMAGE }}

  deploy-prod:
    name: Deploy (prod)
    runs-on: ubuntu-latest
    needs: [ build-and-test, deploy-dev ]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: frontend/nav-enheter-to-sanity/.nais/nais-prod.yaml
          VAR: image=${{ env.IMAGE }}
